---
# -*- coding: utf-8 -*-

before_script:
  - env
  - hostname
  - ip r
  - du --max-depth=1
  - uname -a

stages:
  - shell-check

shell-check:
  stage: shell-check
  script:
    - make chk
  tags:
    - ansible
