---

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-executables-have-shebangs
- repo: https://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
  hooks:
  - id: shell-lint
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    files: ^ipa-api-syn/
