#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

BIN="$(basename "$0")"

function cfg_usage()
{
cat << EOF

## \`$BIN\` Common functions and variables

### Usage

\`\`\`bash

  $BIN

\`\`\`

### Description

Common functions and variables for FreeIPA SSSD Tools scripts.

EOF
}

if [[ "$1" =~ ^[-]+(h|help) ]]
then
  [[ "$BIN" = "$(basename "${BASH_SOURCE[0]}")" ]] && cfg_usage
fi

function die()
{
  echo >&2 "ERROR: $1"
  exit 1
}

markdown()
{
cat << EOF
---
fontsize: 8pt
code-block-font-size: 8pt
classoption: landscape
---
EOF
}

code()
{
  printf "\\n\\n%s\\n\\n" '```'
}

title1()
{
  printf "\\n# %s\\n\\n" "$1"
}

title2()
{
  printf "\\n## %s\\n\\n" "$1"
}

title3()
{
  printf "\\n### %s\\n\\n" "$1"
}
