#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/ipa-src-cfg"

function usage()
{
cat << EOF

## \`$BIN\` Generate and plot metrics in HTML gallery

### Usage

\`\`\`bash

  $BIN [IPA_SSS_SYN_LOG] [YYYY-MM-DD]

\`\`\`

### Description

Split \`ipa-sss-syn.log\` by date, generate \`.dat\` files, plot
between hours range and generate _HTML_ gallery of SynLog Plots Images.

### Example

\`\`\`bash

  $BIN

  /var/www/html/syn/img/2022-11-14-seconds-vs-total-vs-ips-0700-1900.png
  /var/www/html/syn/index.html

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -n "$LOG"    ]] || LOG='ipa-sss-syn.log'
[[ -z "$1"      ]] || LOG="$1"
[[ -e "$LOG"    ]] || die "NOT FOUND FILE $LOG"
[[ -n "$DATE"   ]] || DATE="$(date +%F)"
[[ -z "$2"      ]] || DATE="$2"
[[ -n "$USR"    ]] || USR='root'
[[ -n "$XSTART" ]] || XSTART='07:00'
[[ -n "$XEND"   ]] || XEND='19:00'

ipa-sss-day "$LOG"            "$DATE"
ipa-sss-dat "$DATE-$LOG"      "$DATE"
ipa-sss-plt "$DATE" "$XSTART" "$XEND"
ipa-sss-htm
