#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/ipa-src-cfg"

function usage()
{
cat << EOF

## \`$BIN\` Generate Markdown Table Overview

### Usage

\`\`\`bash

  $BIN

\`\`\`

### Description

Generate a markdown table output for each command script.

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

function title2table()
{

  $1 -h                 \
    | grep '^## '       \
    | head -1           \
    | sed 's/##//g'     \
    | while read -r F D
      do
        printf "| %13s | %-50s |\n" "$F" "$D"
      done

}

printf "| %-13s | %-50s |\n" "script" "description"

find . -maxdepth 1 -type f -executable -iname 'ipa-*' \
  | grep -E 'ipa-[a-z]{3}-[a-z]{3}$'                  \
  | cut -d/ -f2-                                      \
  | sort -u                                           \
  | while read -r F
    do

      TABLE="$(title2table "$F")"
      [[ -z "$TABLE" ]] && TABLE="| \`$F\` | FIXME |"
      echo "$TABLE"

    done
