#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/ipa-src-cfg"

function usage()
{
cat << EOF

## \`$BIN\` Generate HTML gallery of SynLog Plots Images

### Usage

\`\`\`bash

  $BIN

\`\`\`

### Description

Generate HTML gallery of SynLog Plots Images

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

function validate()
{

	[[ -z "$HTM_CSS"          ]] && cfg 'HTM_CSS'
	[[ -z "$HTM_DIR"          ]] && cfg 'HTM_DIR'
	[[ -z "$HTM_INDEX"        ]] && cfg 'HTM_INDEX'
	[[ -z "$HTM_TITLE"        ]] && cfg 'HTM_TITLE'
	[[ -z "$HTM_TPL"          ]] && cfg 'HTM_TPL'
  [[ -z "$HTM_TOP"          ]] && cfg 'HTM_TOP'

	[[ -d "$HTM_DIR"          ]] || die "NOT FOUND DIR $HTM_DIR"

	[[ -e "$HTM_TPL"          ]] || HTM_TPL="$DIR_BIN/$HTM_TPL"
	[[ -e "$HTM_TPL"          ]] || die "NOT FOUND FILE $HTM_TPL"

	[[ -e "$HTM_DIR/$HTM_CSS" ]] || die "NOT FOUND FILE $HTM_DIR/$HTM_CSS"

}

function png2href()
{

cd "$HTM_DIR/img" || exit 1

find . -type f -iname '*.png' \
  | cut -d/ -f2-              \
  | sort -nr                  \
  | head -n "$HTM_TOP"        \
  | while read -r F
    do

N="$(basename "$F")"
D="$(echo "$N" | cut -c -10)"

#FIXME split by week

cat << EOF

  <div class="row">
    <div class="col-sm">
  		<a href="img/$F"><img src="img/$F" alt="$D"/></a>
    </div>
  </div>

EOF

    done

}

function header()
{

cat << EOF

<header>
  <a href="#" class="logo">$HTM_TITLE</a>
</header>

EOF

}

function html()
{

HTML="$(cat "$HTM_TPL")"
HTML="${HTML//<!--=@title-->/${HTM_TITLE}}"
HTML="${HTML//<!--=@css-->/${HTM_CSS}}"

HEADER="$(header)"
HTML="${HTML//<!--+@header-->/${HEADER}}"

CONTENT="$(png2href)"
HTML="${HTML//<!--+@content-->/${CONTENT}}"

echo "$HTML" > "$HTM_DIR/$HTM_INDEX"

}

function main()
{
  config
  validate
  html
}

main
