#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/ipa-src-cfg"

function usage()
{
cat << EOF

## \`$BIN\` Split SynLog by user

### Usage

\`\`\`bash

  $BIN [IPA_SSS_SYN_LOG] [YYY-MM-DD]

\`\`\`

### Description

Split \`ipa-sss-syn.log\` by user.

### Examples

\`\`\`bash

  $BIN ipa-sss-syn.log root

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

DATE="$(date +%F)"
LOG="$DATE-ipa-sss-syn.log"
TMP="$(mktemp)"

[[ -z "$1"   ]] || LOG="$1"
[[ -e "$LOG" ]] || die "NOT FOUND LOG FILE $LOG"
[[ -z "$2"   ]] || DATE="$2"

grep -E "^$DATE " "$LOG" > "$TMP"

USER_LST="$(mktemp)"

if [[ -z "$3" ]]
then
  awk '{print $3}'    "$TMP" | cut -d '=' -f2 | sort -u > "$USER_LST"
else
  grep -w " user=$3 " "$TMP" | cut -d '=' -f2 | sort -u > "$USER_LST"
fi

rm -f "$TMP"

mkdir -p bak

while read -r USR _
do

  USER_LOG="$USR-$DATE-$LOG"
  USER_LOG="${USER_LOG/$DATE-$DATE/$DATE}"
  USER_BAK="bak/$USR-$LOG.$(date +%s)"

  [[ -e "$USER_LOG" ]] && cp -f "$USER_LOG" "$USER_BAK"

  grep -E " user=$USR " "$LOG" > "$USER_LOG"
  TOTAL="$(wc -l "$USER_LOG")"

  printf "\\n%6s %s" "${TOTAL%%" "*}" "$USER_LOG"

done < "$USER_LST"

rm -f "$USER_LST"
echo
